services:
  grpc-server:
    build: ./grpc-server
    container_name: grpc-server
    ports:
      - "50051:50051"
    volumes:
      - grpc-server:/app/media
    
    environment:
      GRPC_SERVER_PORT: 50051
      MAX_WORKERS: 10
      MEDIA_PATH: /app/media
      DBNAME: mydatabase
      DBUSERNAME: postgres
      DBPASSWORD: postgres
      DBHOST: db
      DBPORT: 5432
      PYTHONBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PW: guest
    
    depends_on:
      - db

  rest-api-server:
    build: ./rest_api_server
    container_name: rest_api_server
    ports:
      - "8000:8000"
    environment:
      GRPC_PORT: 50051
      GRPC_HOST: grpc-server
      DBNAME: mydatabase
      DBUSERNAME: postgres
      DBPASSWORD: postgres
      DBHOST: db
      DBPORT: 5432

    depends_on:
      - grpc-server
      - db

  graphql-server:
    build: ./graphql_server
    container_name: graphql-server
    ports:
      - "8001:8001"
    environment:
      GRPC_PORT: 50051
      GRPC_HOST: grpc-server
      DBNAME: mydatabase
      DBUSERNAME: postgres
      DBPASSWORD: postgres
      DBHOST: db
      DBPORT: 5432
    depends_on:
      - grpc-server
      - db

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  worker:
    build: ./worker-rabbit-csv
    ports:
      - "8003:8003"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PW: guest
      DBNAME: mydatabase
      DBUSERNAME: postgres
      DBPASSWORD: postgres
      DBHOST: db
      DBPORT: 5432
    depends_on:
      - rabbitmq
      - db
      - grpc-server

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REST_API_BASE_URL: http://rest-api-server:8000
      GRAPHQL_API_BASE_URL: http://graphql-server:8001
      NEXT_PUBLIC_URL: http://frontend:3000
      CRSF_COOKIE: xQjKRQfI8PMAubfyUWElWsp6k7r9BLaE
    depends_on:
      - rest-api-server
      - graphql-server
      - grpc-server
      - rabbitmq
      - db

volumes:
  grpc-server:
  pgdata:

