# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import server_services_pb2 as server__services__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in server_services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImporterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadCSV = channel.unary_unary(
                '/server_services.ImporterService/UploadCSV',
                request_serializer=server__services__pb2.FileUploadRequest.SerializeToString,
                response_deserializer=server__services__pb2.FileUploadResponse.FromString,
                _registered_method=True)
        self.UploadCSVChunks = channel.stream_unary(
                '/server_services.ImporterService/UploadCSVChunks',
                request_serializer=server__services__pb2.FileUploadChunksRequest.SerializeToString,
                response_deserializer=server__services__pb2.FileUploadChunksResponse.FromString,
                _registered_method=True)


class ImporterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadCSV(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadCSVChunks(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImporterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadCSV': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadCSV,
                    request_deserializer=server__services__pb2.FileUploadRequest.FromString,
                    response_serializer=server__services__pb2.FileUploadResponse.SerializeToString,
            ),
            'UploadCSVChunks': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadCSVChunks,
                    request_deserializer=server__services__pb2.FileUploadChunksRequest.FromString,
                    response_serializer=server__services__pb2.FileUploadChunksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server_services.ImporterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('server_services.ImporterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImporterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadCSV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_services.ImporterService/UploadCSV',
            server__services__pb2.FileUploadRequest.SerializeToString,
            server__services__pb2.FileUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadCSVChunks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/server_services.ImporterService/UploadCSVChunks',
            server__services__pb2.FileUploadChunksRequest.SerializeToString,
            server__services__pb2.FileUploadChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GroupByServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FilterXML = channel.unary_unary(
                '/server_services.GroupByService/FilterXML',
                request_serializer=server__services__pb2.FilterRequest.SerializeToString,
                response_deserializer=server__services__pb2.FilterResponse.FromString,
                _registered_method=True)
        self.SearchXML = channel.unary_unary(
                '/server_services.GroupByService/SearchXML',
                request_serializer=server__services__pb2.SearchRequest.SerializeToString,
                response_deserializer=server__services__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GroupXML = channel.unary_unary(
                '/server_services.GroupByService/GroupXML',
                request_serializer=server__services__pb2.GroupRequest.SerializeToString,
                response_deserializer=server__services__pb2.GroupResponse.FromString,
                _registered_method=True)
        self.OrderXML = channel.unary_unary(
                '/server_services.GroupByService/OrderXML',
                request_serializer=server__services__pb2.OrderRequest.SerializeToString,
                response_deserializer=server__services__pb2.OrderResponse.FromString,
                _registered_method=True)


class GroupByServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FilterXML(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchXML(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GroupXML(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OrderXML(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroupByServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FilterXML': grpc.unary_unary_rpc_method_handler(
                    servicer.FilterXML,
                    request_deserializer=server__services__pb2.FilterRequest.FromString,
                    response_serializer=server__services__pb2.FilterResponse.SerializeToString,
            ),
            'SearchXML': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchXML,
                    request_deserializer=server__services__pb2.SearchRequest.FromString,
                    response_serializer=server__services__pb2.SearchResponse.SerializeToString,
            ),
            'GroupXML': grpc.unary_unary_rpc_method_handler(
                    servicer.GroupXML,
                    request_deserializer=server__services__pb2.GroupRequest.FromString,
                    response_serializer=server__services__pb2.GroupResponse.SerializeToString,
            ),
            'OrderXML': grpc.unary_unary_rpc_method_handler(
                    servicer.OrderXML,
                    request_deserializer=server__services__pb2.OrderRequest.FromString,
                    response_serializer=server__services__pb2.OrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server_services.GroupByService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('server_services.GroupByService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GroupByService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FilterXML(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_services.GroupByService/FilterXML',
            server__services__pb2.FilterRequest.SerializeToString,
            server__services__pb2.FilterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchXML(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_services.GroupByService/SearchXML',
            server__services__pb2.SearchRequest.SerializeToString,
            server__services__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GroupXML(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_services.GroupByService/GroupXML',
            server__services__pb2.GroupRequest.SerializeToString,
            server__services__pb2.GroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OrderXML(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_services.GroupByService/OrderXML',
            server__services__pb2.OrderRequest.SerializeToString,
            server__services__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
